version: "3.8"
services:
  mestre:
    build:
      context: .
      dockerfile: Dockerfile-mestre
    ports:
      - "8080:8080"
    depends_on:
      - escravo-letras
      - escravo-numeros

  escravo-letras:
    build:
      context: .
      dockerfile: Dockerfile-letras
    ports:
      - "8081:8081"

  escravo-numeros:
    build:
      context: .
      dockerfile: Dockerfile-numeros
    ports:
      - "8082:8082"
